### ISSUE TITLE
Flash-Player rule does not work for major version bumps

### ISSUE THREAD

**Issue by guiweber** [just-install/just-install-updater#12]
We need to add a way to insert only part of the version number in the base link.

**Comment by Schokobecher** [comment]
This wouldn't only benefit Adobe Flashplayer, but also a few packages that I have been planning on adding later on.

For exmaple the current version scheme is something like: XX.YY.ZZZ
Either we hardcode another `{{.version}}` variable for each section, or we need to dynamically split each section.

Getting the `24` for Flashplayer is rather easy:

`.+?(?=\.)` would result in `XX`

**Comment by guiweber** [comment]
@Schokobecher I implemented placeholders only for the first three parts of a version number (simple hard-coded replacement for each). I think this will be fine, but let me know if you need more flexibility.
