### ISSUE TITLE
Eclipse-android removed to make build pass

### ISSUE THREAD

**Issue by guiweber** [just-install/just-install-updater#21]
Eclipse-android hasn't been added to the package list since the release of Oxygen, which prevents retrieving the latest version.

https://www.eclipse.org/downloads/packages/

The rule will be removed until the package is added back to the package list.

**Comment by guiweber** [comment]
The original rule for reference:
``` 
"eclipse-android": {
    "url": "https://eclipse.org/downloads/eclipse-packages/",
    "append": "&r=1",
    "updater": {
      "x86": {
        "rule_type": "css-link",
        "selector": "a[href$='win32.zip']",
        "filter": "eclipse-android"
      },
      "x86_64": {
        "rule_type": "css-link",
        "selector": "a[href$='win32-x86_64.zip']",
        "filter": "eclipse-android"
      }
    },
    "version_extractor": "<span id=\"descriptionText\">.*\\(([0-9]*(?:\\.[0-9]+)*[a-z]?)\\)",
    "version_source": "page"
  },
```

**Comment by cyagon** [comment]
eclipse-android is deprecated and got replaced by Android Studio: https://android-developers.googleblog.com/2015/06/an-update-on-eclipse-android-developer.html
