### ISSUE TITLE
crystaldiskinfo/mark rule not working anymore

### ISSUE THREAD

**Issue by cyagon** [just-install/just-install-updater#60]
it seems like the 'advanced' rules for both programs arent working anymore.
Here are baselinks that will hopefully work better, but unfortunately I have not made it yet:

https://ftp.halifax.rwth-aachen.de/osdn/crystaldiskinfo/
https://ftp.halifax.rwth-aachen.de/osdn/crystaldiskmark/

@geek1011 @guiweber

**Comment by geek1011** [comment]
This should be fixed now.
