### ISSUE TITLE
updater currently broken

### ISSUE THREAD

**Issue by cyagon** [just-install/just-install-updater#62]
the current updater does not check for new versions. tested with latest node-lts.

![2018-04-12_19-38-34](https://user-images.githubusercontent.com/32183089/38695641-24b48de8-3e8d-11e8-8900-6bdeb2dc2096.gif)

**Comment by geek1011** [comment]
I know. I'm not sure what's happening, as I only touched the cli init function. For now, use the version before I started refactoring, or I could revert it if you want.

**Comment by cyagon** [comment]
it would be nice if you could revert it, or move the latest cli-init changes to another branch ("dev"?).

**Comment by geek1011** [comment]
@cyagon OK, I'll do that.

**Comment by cyagon** [comment]
also: it would be nice if you can look over https://github.com/just-install/just-install/issues/235 . if x86_64 only entries are implemented, we can bump the just-install version to 3.5 and i can add multiple x86_64 only programs (mysql-workbench for example).

**Comment by geek1011** [comment]
@cyagon I've moved it to a new branch. As for x64-only entries, I'll implement that in the new updater and just-install as soon as I finish the first version of the new updater.

**Comment by cyagon** [comment]
@geek1011 ok. thank you :)
